name: multiagent-baseline
phase: forecast

target:
  _target_: src.model.multiagent.trainer_forecast_ma.Trainer
  dim: 128
  historical_steps: 50
  future_steps: 60
  encoder_depth: 4
  num_heads: 8
  mlp_ratio: 4.0
  qkv_bias: False
  drop_path: 0.2
  num_modes: 6
  use_cls_token: false
  lr: ${lr}
  weight_decay: ${weight_decay}
  epochs: ${epochs}
  warmup_epochs: ${warmup_epochs}
